# Generated by Django 4.2.11 on 2024-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_linked_to_dana', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('create_by', models.BigIntegerField(null=True)),
                ('update_by', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
