# Generated by Django 4.2.11 on 2024-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dana_integration_api_app', '0001_create_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_by',
            new_name='updated_by',
        ),
    ]
